#!/bin/bash
branch_name=`git rev-parse --abbrev-ref HEAD`
tag=${1:-$branch_name}

if [ $tag == "main" ]
then
    echo "Read the docs: https://github.com/skit-ai/skit-pipelines/blob/main/CONTRIBUTING.md"
    exit 0
fi

source secrets/env.sh && docker build \
    --build-arg BASE_IMAGE=$BASE_IMAGE:$tag \
    --build-arg CUDA_IMAGE=$CUDA_IMAGE:$tag \
    --build-arg DB_HOST=$DB_HOST \
    --build-arg DB_PORT=$DB_PORT \
    --build-arg DB_PASSWORD=$DB_PASSWORD \
    --build-arg DB_NAME=$DB_NAME \
    --build-arg DB_USER=$DB_USER \
    --build-arg CDN_RECORDINGS_BASE_PATH=$CDN_RECORDINGS_BASE_PATH \
    --build-arg BUCKET=$BUCKET \
    --build-arg SLACK_TOKEN=$SLACK_TOKEN \
    --build-arg SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET \
    --build-arg DEFAULT_SLACK_CHANNEL=$DEFAULT_SLACK_CHANNEL \
    --build-arg TOG_TASK_URL=$TOG_TASK_URL \
    --build-arg LABELSTUDIO_TOKEN=$LABELSTUDIO_TOKEN \
    --build-arg SKIT_API_GATEWAY_PASSWORD=$SKIT_API_GATEWAY_PASSWORD \
    --build-arg SKIT_API_GATEWAY_EMAIL=$SKIT_API_GATEWAY_EMAIL \
    --build-arg SKIT_API_GATEWAY_URL=$SKIT_API_GATEWAY_URL \
    --build-arg KUBEFLOW_GATEWAY_ENDPOINT=$KUBEFLOW_GATEWAY_ENDPOINT \
    --build-arg KF_USERNAME=$KF_USERNAME \
    --build-arg KF_PASSWORD=$KF_PASSWORD \
    --build-arg GOOGLE_SHEETS_CREDENTIALS=$GOOGLE_SHEETS_CREDENTIALS \
    --build-arg KAFKA_INSTANCE=$KAFKA_INSTANCE -t $ECR_REPOSITORY . -f Dockerfile \
    && docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$tag \
    && docker push $ECR_REGISTRY/$ECR_REPOSITORY:$tag
