FROM 536612919621.dkr.ecr.ap-south-1.amazonaws.com/vernacular-voice-services/ai/kubeflow/base-py:master

WORKDIR /home/kfp

RUN apt-get update \
    && apt-get install -y wget gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry
RUN poetry config virtualenvs.create false

COPY . .
RUN poetry install --no-dev

ARG BASE_IMAGE
ARG DB_HOST
ARG DB_PORT
ARG DB_PASSWORD
ARG DB_NAME
ARG DB_USER
ARG RANDOM_CALL_DATA_QUERY
ARG RANDOM_CALL_ID_QUERY
ARG CDN_RECORDINGS_BASE_PATH
ARG BUCKET
ARG SLACK_TOKEN
ARG DEFAULT_SLACK_CHANNEL
ARG SKIT_API_GATEWAY_URL
ARG SKIT_API_GATEWAY_EMAIL
ARG SKIT_API_GATEWAY_PASSWORD
ARG API_GATEWAY
ARG TOG_TASK_URL

ENV BASE_IMAGE=$BASE_IMAGE
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV RANDOM_CALL_DATA_QUERY=$RANDOM_CALL_DATA_QUERY
ENV RANDOM_CALL_ID_QUERY=$RANDOM_CALL_ID_QUERY
ENV CDN_RECORDINGS_BASE_PATH=$CDN_RECORDINGS_BASE_PATH
ENV BUCKET=$BUCKET
ENV SLACK_TOKEN=$SLACK_TOKEN
ENV DEFAULT_SLACK_CHANNEL=$DEFAULT_SLACK_CHANNEL
ENV SKIT_API_GATEWAY_URL=$SKIT_API_GATEWAY_URL
ENV SKIT_API_GATEWAY_EMAIL=$SKIT_API_GATEWAY_EMAIL
ENV SKIT_API_GATEWAY_PASSWORD=$SKIT_API_GATEWAY_PASSWORD
ENV API_GATEWAY=$API_GATEWAY
ENV TOG_TASK_URL=$TOG_TASK_URL

CMD ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
