[tool.poetry]
name = "skit-pipelines"
version = "0.1.1"
description = "Kubeflow components for ml workflows at skit.ai."
authors = ["ltbringer <amresh.venugopal@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
skit-calls = "^0.2.1"
loguru = "0.5.3"
boto3 = "^1.21.23"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
