asr_config:
  execution_type: default
  references:
    - provider: GOOGLE
      recognition_config:
        language_code: hi
        sample_rate_hertz: 8000
        max_alternatives: 10
        model: default
        ontology_terms:
          - काहे का
          - एजेंट एजेंट एजेंट एजेंट
          - वहां जाकर देना पड़ेगा अब बैंक में चोलामंडल में
          - अरे यार वो व्यवस्था नहीं है इस लिए नहीं कर पा रहे पेमेंट
          - ये एजेंट को दूंगा में कैश में क्योंकि अकाउंट से तो कटे नहीं है