asr_config:
  execution_type: default
  references:
    - provider: KALDI_SERVE
      recognition_config:
        model: general-v41
        language_code: hi
        sample_rate_hertz: 8000
        max_alternatives: 10