name: Build Pipelines

on:
  push:
     tags:
     - '*'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set currently pushed tag as env var.
        id: set-tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          RANDOM_CALL_DATA_QUERY: ${{ secrets.RANDOM_CALL_DATA_QUERY }}
          RANDOM_CALL_ID_QUERY: ${{ secrets.RANDOM_CALL_ID_QUERY }}
          CDN_RECORDINGS_BASE_PATH: ${{ secrets.CDN_RECORDINGS_BASE_PATH }}
          BUCKET: ${{ secrets.BUCKET }}
          DATA_UPLOAD_PATH: ${{ secrets.DATA_UPLOAD_PATH }}
        run: "docker build \
          --build-arg BASE_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_VERSION \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg DB_USER=$DB_USER \
          --build-arg RANDOM_CALL_DATA_QUERY=$RANDOM_CALL_DATA_QUERY \
          --build-arg RANDOM_CALL_ID_QUERY=$RANDOM_CALL_ID_QUERY \
          --build-arg CDN_RECORDINGS_BASE_PATH=$CDN_RECORDINGS_BASE_PATH \
          --build-arg BUCKET=$BUCKET \
          --build-arg DATA_UPLOAD_PATH=$DATA_UPLOAD_PATH -t $ECR_REPOSITORY ."

      - name: Tag and push images
        env: 
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_VERSION
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:master
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:master
